services:
  - type: web
    name: recetas-api
    env: dotnet
    plan: free
    buildCommand: "dotnet restore ./MiApiRecetas/MiApiRecetas.csproj && dotnet publish ./MiApiRecetas/MiApiRecetas.csproj -c Release -o out"
    startCommand: "dotnet out/MiApiRecetas.dll"
    envVars:
      - key: ConnectionStrings__SqlServer
        sync: false   # Render usará la variable que ya configuraste en el panel
